"""Launcher for {{EXE_NAME}}.

Generated by synapseForge — do not edit manually.
Uses embedded Python to run the FastAPI server.
Opens the browser automatically after startup.
"""

import os
import subprocess
import sys
import threading
import time


# Project-specific values (injected by forge.py)
APP_MODULE = "{{APP_MODULE}}"
PORT = "{{PORT}}"
EXE_NAME = "{{EXE_NAME}}"


def _open_browser(url: str, delay: int = 4) -> None:
    """Open the browser after a short delay to let the server start."""
    import webbrowser
    time.sleep(delay)
    webbrowser.open(url)


def main() -> None:
    # Determine project root: exe location when frozen
    if getattr(sys, "frozen", False):
        base_dir = os.path.dirname(sys.executable)
    else:
        # Development: go up from __forge_build__/
        base_dir = os.path.dirname(
            os.path.dirname(os.path.abspath(__file__))
        )
    os.chdir(base_dir)

    python_dir = os.path.join(base_dir, "python")
    python_exe = os.path.join(python_dir, "python.exe")

    # Verify embedded Python exists
    if not os.path.isfile(python_exe):
        if hasattr(sys, "stdin") and sys.stdin is not None:
            input(
                f"Error: No se encuentra Python embebido en:\n"
                f"  {python_exe}\n\n"
                "Asegurate de que la carpeta python/ existe.\n\n"
                "Presiona Enter para salir..."
            )
        sys.exit(1)

    # Open browser in background
    threading.Thread(
        target=_open_browser,
        args=("http://localhost:" + PORT,),
        daemon=True,
    ).start()

    # Run uvicorn via embedded Python (no hardcoded paths)
    cmd = [
        python_exe, "-m", "uvicorn",
        APP_MODULE,
        "--host", "localhost",
        "--port", PORT,
    ]
    creation_flags = 0
    if sys.platform == "win32":
        creation_flags = subprocess.CREATE_NO_WINDOW
    proc = subprocess.run(cmd, shell=False, creationflags=creation_flags)

    if proc.returncode != 0:
        pass
    else:
        pass


if __name__ == "__main__":
    main()
